### ISSUE TITLE
Will create a home page

### ISSUE THREAD

**Issue by BxtGeek** [abhinavkashyap061/Dear-Diary#1]

**Comment by abhinavkashyap061** [comment]
Umm, okay. Can you please elaborate on what will it consist as all the required sections are **already present** on the navbar already 😅

**Comment by atom540** [comment]
can you please assign it to me?

**Comment by abhinavkashyap061** [comment]
Hey @atom540  👋, Thanks for considering contributing to my project

- Okay sure! i am assigning it to you 👍

Happy Hacking 🚀

**Comment by Kritika30032002** [comment]
can you assign it to me? May I contribute to this?
