### ISSUE TITLE
UI change

### ISSUE THREAD

**Issue by smrkarkii** [abhinavkashyap061/Dear-Diary#11]
In create section, it would be better if the color of input fields is darker color. Please assign it to me under hacktoberfest.
![colorr](https://user-images.githubusercontent.com/58778838/194903439-c3b0daf7-7fbc-436b-866f-f225a4ca4760.png)

**Comment by abhinavkashyap061** [comment]
Hey @smrkarkii  👋, Thanks for considering contributing to my project

- ok nice observation, i am assigning you this task 👍

Happy Hacking 🚀

**Comment by Kritika30032002** [comment]
may i contribute to this?
