### ISSUE TITLE
Navbar is overlapping with Heading in Mobile Layout

### ISSUE THREAD

**Issue by SujalSamai** [abhinavkashyap061/Dear-Diary#2]
When we check the mobile layout of the website, the home button in the navbar overlaps with the heading, which looks odd.
I would like to sort this issue, if you can assign me the problem and make appropriate changes.
![image](https://user-images.githubusercontent.com/87236576/194695822-a7b1daf5-9d60-4c24-8b38-c1f58a8c605c.png)

**Comment by abhinavkashyap061** [comment]
Hey @SujalSamai great observation mate! I'm assigning you this issue 👍

**Comment by SujalSamai** [comment]
> Hey @SujalSamai great observation mate! I'm assigning you this issue 👍

Thankss, will raise a PR ASAP!
