### ISSUE TITLE
putting footer at at the bottom of the of the webpage

### ISSUE THREAD

**Issue by Antoniohayato** [abhinavkashyap061/Dear-Diary#23]
we can make page more interesting by adding background image , provide the button to add images , hand scribbling area, calender,dates on each page

**Comment by DexLulz** [comment]
I can do this.

**Comment by abhinavkashyap061** [comment]
> we can make page more interesting by adding background image , provide the button to add images , hand scribbling area, calender,dates on each page

that's an overkill tbh.
