### ISSUE TITLE
Created a new logo and change it in Dear-Diary/views/partials/header.ejs

### ISSUE THREAD

**Issue by EXPOLK** [abhinavkashyap061/Dear-Diary#29]
Created a logo for this project and changed the script in (Dear-Diary/views/partials/header.ejs\)
![dear-diary-logo](https://user-images.githubusercontent.com/109457188/195505585-9bddfd18-7e8b-418a-a605-adb7da446457.png)

**Comment by abhinavkashyap061** [comment]
wow @EXPOLK that is amazing mate! I am assigning you this task!

**Comment by EXPOLK** [comment]
Bro can you please assign the hacktoberfest accepted label to my pull
request?

**Comment by abhinavkashyap061** [comment]
sure

**Comment by EXPOLK** [comment]
Thanks a lot.

**Comment by DarkSoul26** [comment]
@abhinavkashyap061 I would like to work on this issue.
