### ISSUE TITLE
Frontend improvements

### ISSUE THREAD

**Issue by subrato3** [abhinavkashyap061/Dear-Diary#5]
There can be some improvements on the frontend ui
1. Favicon can be added to the tab
2. In the contact us section, social media icons can be added instead of their name. This will give a uniformity to the start of the links
3. These social media icons can be added in the footer too with hover animation

please assign me to work on these issues

**Comment by abhinavkashyap061** [comment]
Hey @subrato3 👋, Thanks for considering contributing to my project

nice attention to detail, i am assigning you this issue 👍

Happy Hacking 🚀

**Comment by abhinavkashyap061** [comment]
Hey @subrato3 👋

thanks for contributing <3

Happy Hacking 🚀
