### ISSUE TITLE
the website does not have an opengraph card

### ISSUE THREAD

**Issue by jagadyudha** [abhinavkashyap061/Dear-Diary#6]
![image](https://user-images.githubusercontent.com/41937681/194733255-67985e81-1313-4f58-b0df-13614812d7cf.png)

Please assign to me @abhinavkashyap061

**Comment by abhinavkashyap061** [comment]
Hey @jagadyudha  👋, Thanks for considering contributing to my project

ok 👍

Happy Hacking 🚀
