### ISSUE TITLE
Footer bug

### ISSUE THREAD

**Issue by abhinavkashyap061** [abhinavkashyap061/Dear-Diary#9]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/84775901/194894816-31e1034b-0d82-4d96-928b-8987b671b67f.png">

**Comment by syprogrammer** [comment]
please assign me

**Comment by AvadhootK** [comment]
Hey @abhinavkashyap061 , can you tell me how do I run the project on local machine?

**Comment by shriya-tiwari** [comment]
I would like to work on this issue.

**Comment by anubhav2102** [comment]
I would like to work on this issue

**Comment by sri-rishi** [comment]
I would like to work on this issue

**Comment by AnshuSarkarANX** [comment]
I have faced the same problem with my [blog website](https://github.com/AnshuSarkarANX/Blog-Website) and I fixed it, I can easily fix this if you assign me this issue.
